<template>
  <main>
    <InnerTop heading="Privacy Policy"/>
    <section class="pt-112 pt-152-sm pb-80 pb-192-sm">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <HelperText class="mb-24">Privacy Policy</HelperText>
            <h2 class="mb-64 mb-80-sm word-split">We care about your privacy and are committed to safeguarding your personal information.</h2>
            
            <div class="privacy-content">
              <div class="mb-48 mb-64-sm">
                <p>Sheba Gold Capital, (referred to here as "we," us" or ours") is committed to protecting your privacy and developing technology that gives you the most powerful and safe online experience. This Statement of Privacy applies to the sheba.gold website and governs data collection and usage. By using our website, you consent to the data practices described in this statement.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Collection of Your Personal Information</h3>
                <p class="mb-16">When you visit the site, there is data that may be collected. This information can include: your IP address, browser type, domain names, access times and referring website addresses. This information is used by Sheba Gold Capital for the operation of the service, to maintain quality of the service, and to provide general statistics regarding use of our website. sheba.gold also keeps track of the websites and pages our customers visit within our site to determine what services are the most popular. This data is used to deliver customized content and advertising within sheba.gold to customers whose behavior indicates that they are interested in a particular subject area.</p>
                <p class="mb-16">We may collect personal information you voluntarily provide to us including your name, e-mail address, and phone number.</p>
                <p>Sheba Gold Capital encourages you to review the privacy statements of websites you choose to link to from our site so that you can understand how those websites collect, use and share your information. We are not responsible for the privacy statements or other content on websites outside of the sheba.gold.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Google Analytics</h3>
                <p class="mb-16">This website uses Google Analytics to help analyze how users use the site, which uses cookies. Cookies are used to collect standard Internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about your use of the website (including IP address) is transmitted to Google. This information is then used to evaluate visitors' use of the website and to compile statistical reports on website activity for sheba.gold.</p>
                <p class="mb-16">Google Analytics collects information anonymously. Google will not associate your IP address with any other data held by Google. Neither Sheba Gold Capital nor Google will link, or seek to link, an IP address with the identity of a computer user. We will not associate any data gathered from this site with any Personally Identifiable Information from any source, unless you explicitly submit that information via a fill-in form on our website. Google Analytics reports website trends without identifying individual visitors. You can opt out of Google Analytics without affecting how you visit our site – for more information on opting out of being tracked by Google Analytics across all websites you use, visit <a href="https://support.google.com/analytics/answer/181881?hl=en" target="_blank" rel="noopener noreferrer" class="text-link">this Google page</a>.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Use of Cookies</h3>
                <p class="mb-16">The Sheba Gold Capital website uses "cookies" to help you personalize your online experience. A cookie is a text file that is placed on your hard disk by a Web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you.</p>
                <p class="mb-16">One of the primary purposes of cookies is to provide a convenience feature to save you time. The purpose of a cookie is to tell the Web server that you have returned to a specific page. For example, if you personalize sheba.gold pages, or register with the sheba.gold site or services, a cookie helps sheba.gold to recall your specific information on subsequent visits. This simplifies the process of recording your personal information. When you return to the same sheba.gold website, the information you previously provided can be retrieved, so you can easily use the sheba.gold features that you customized.</p>
                <p>You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of our site or Web sites you visit.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Use of Your Personal Information</h3>
                <p class="mb-16">sheba.gold collects and uses your personal information to operate our website and deliver the services you have requested. We also use your personally identifiable information to inform you of other products or services available from sheba.gold or its affiliates. We may also contact you via surveys to conduct research about your opinion of current services or of potential new services that may be offered.</p>
                <p class="mb-16">We do not sell, rent or lease customer lists to third parties. We may, from time to time, contact you on behalf of external business partners about a particular offering that may be of interest to you. In those cases, your unique personally identifiable information (e-mail, name, address, telephone number) is not transferred to the third party. In addition, we may share data with trusted partners to help us perform statistical analysis, send you email or postal mail, provide customer support, or arrange for deliveries. All such third parties are prohibited from using your personal information except to provide these services to us, and they are required to maintain the confidentiality of your information.</p>
                <p>We will disclose your personal information, without notice, only if required to do so by law or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on sheba.gold; (b) protect and defend the rights or property of sheba.gold; and, (c) act under exigent circumstances to protect the personal safety of users of sheba.gold or the public.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Security of Your Personal Information</h3>
                <p class="mb-16">Sheba Gold Capital secures your personal information from unauthorized access, use or disclosure.</p>
                <p>We secure the personally identifiable information you provide on computer servers in a controlled, secure environment, protected from unauthorized access, use or disclosure.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">California Consumer Privacy Act</h3>
                <p class="mb-16">Residents of California have the right to request certain personally identifiable information shared with third parties by a business with whom the California resident has an established business relationship as well as the names of the third parties with whom the information has been shared. In addition, an operator of a commercial website subject to California Business and Professions Code Section 22581 is required to fulfill requests from California residents under age 18 who are registered users of online sites, services or applications to obtain removal of content or information they have publicly posted.</p>
                <p>If this applies to you and you wish to request this information, ensure that your request includes a detailed description of the specific content or information to be removed. Please be aware that your request does not guarantee complete or comprehensive removal of content or information posted online and that the law may not permit or require removal in certain circumstances. If you are a California resident, believe that one of the above code provisions applies to you, and would like to make such a request, you may e-mail your request to: info@shebagold.com.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Changes to This Statement</h3>
                <p>Sheba Gold Capital will occasionally update this Statement of Privacy to reflect company and customer feedback. We encourage you to periodically review this Statement to be informed of how our site is protecting your information.</p>
              </div>

              <div class="mb-48 mb-64-sm">
                <h3 class="mb-24">Contact Information</h3>
                <p class="mb-16">Sheba Gold Capital welcomes your comments regarding this Statement of Privacy. If you believe that we have not adhered to this Statement, please contact us at info@shebagold.com. We will use commercially reasonable efforts to promptly determine and remedy the problem.</p>
              </div>

            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup>
import InnerTop from '~/components/InnerTop.vue';
import HelperText from "~/components/elements/HelperText.vue";

useHead({
  title: 'Privacy Policy',
  meta: [
    {
      name: 'description',
      content: 'Learn about how Sheba Gold Capital collects, uses, and protects your personal information. Read our comprehensive privacy policy.'
    }
  ]
});
</script>

<style lang="scss" scoped>
.privacy-content {
  h3 {
    color: rgb(var(--color-gold));
  }

}
</style>